#!/bin/bash

# File:   pre-commit
# Author: earendelmir
# Date:   17 Apr 2024
# Brief:  Check if committing any page that requires to set the 'last updated'
#         date. Abort commit if the date is not set to today.

set -eo pipefail

files=(
    "docs/about/now.html"
    "docs/favourites/index.html"
    "docs/readings/index.html"
    "docs/todo/index.html"
)

for file in "${files[@]}"; do
    # Check if file is being committed.
    if git diff --cached --name-only | grep -q "$file" ; then
        # Get 'last updated' date declared in the file.
        lud="$(grep "last updated" "$file" | cut -d':' -f2 | cut -d'<' -f1)"
        lud="$(echo "$lud" | xargs echo)"  # Trim whitespace.
        # Check if date is today.
        if [[ "$lud" != "$(date '+%d %b %Y')" ]]; then
            printf "\e[1;31m✗ \e[0mBad Last Update Date for: %s\n" "$file"
            abort=1
        fi
    fi
done

[[ -z $abort ]] && exit 0
printf "Change the date, or run git commit with --no-verify option.\n"
exit 1
